-- Amenitra's Marketing Command Center — Seed Data
-- Run this in Supabase SQL Editor AFTER running the schema

-- Accounts
INSERT INTO accounts (id, name, initials, industry, industry_id, status, health, revenue, market_position, signals, pain_hierarchy, goals, target_audience, services, tactics, channels, stakeholders, strategy, last_touch) VALUES
('boa', 'Bank of America', 'BA', 'Financial Services', 'fs', 'key', 88, '$102M', 'Powers BOA execution across AML, cloud, and AI. Key account with strong infrastructure partnership. Competitive pressure from Oxford, Capgemini, Slalom.', '["Third-party risk governance tightening","Data privacy and cross-border compliance increasing","Open banking readiness","Financial crime, AML, KYC acceleration"]', '["Cost, conversion, scalability objections","Need customization vs rigid models","Enablement gaps: thought leadership, AI proof","Talent Services not landing — needs positioning","Competitor pressure: Oxford, Capgemini, Slalom"]', '["Protect/expand AML + Financial Crimes","Advance AI + Cloud position","Credibility driving sales enablement","Strengthen stakeholder access"]', '["Procurement/Vendor Management","Financial Crimes/AML leaders","Infrastructure/Cloud Leaders","AI/Data leaders","Fraud/Security stakeholders"]', '["AML program delivery","Fraud protection support","Tech delivery + infrastructure","Staff aug for cloud environments","Expansion: Crimes/AML, Cloud, AI"]', '["Web — new messaging + global","Thought Leadership — AI, AML outcomes","Brand Advocacy — Charlotte sales leaders","Local Activation — Charlotte momentum","Sales enablement — case studies into BOA assets"]', '["Email & ABM","Content & SEO","Web","Paid Media","Events & Field"]', '["Grace Han"]', '', '2026-04-05'),
('sf', 'State Farm', 'SF', 'Financial Services', 'fs', 'new-logo', 45, '$2M', 'Navigating digital transformation + catastrophic loss recovery. Net income $12.9B in 2025. New CDAO Jon Francis appointed March 2026. Deploying AI for claims triage via OpenAI. Goal: turn ATL proximity into partnership.', '["Net income $12.9B, revenue $132.3B (+7.5% YoY)","$3.1B homeowners underwriting loss (improved from $3.6B)","Jon Francis promoted to CDAO + Head of Digital","Dual digital leadership: Francis + Joe Park as EVP/CDIO","AI claims triage via OpenAI Frontier platform","Digital knowledge assistant for contact centers"]', '["AI/ML talent for claims automation — competing nationally","Data/analytics hiring surge under new CDAO mandate","Digital product/UX engineers for platform modernization","Transformation speed vs homeowners loss management","Property insurance cat-risk and climate modeling talent gap"]', '["Turn ATL proximity into partnership","Reposition from OSP vendor to trusted delivery partner","Earn CSP eligibility (Tech + Non-Tech)","$2M 2026 revenue goal","Measurable CSP milestone progress"]', '["Procurement: Vendor Mgmt, Directors, Category Leads","Claims/Underwriting: Directors/VP, Ops Managers","Data + Tech: Head of Data, AI/Automation Leaders"]', '["Cost Optimization — reduce spend without risk","Rapid Response — surge support for operations","Tech Scale — data delivery + AI-ready foundations"]', '["Web — Insurance page with OSP/CSP language","Social/PR — organic through IG SMEs, local PR","Brand Advocacy — LinkedIn credibility coaching","TL Ads — targeted to top-of-funnel","Local Activation — ATL IG experience sessions","IP-based customization for SF contacts","Proof pack: case snapshots + metrics"]', '["Paid Media","Email & ABM","Web","Organic Social","Events & Field","Content & SEO"]', '["Charlie Loveall","Rachel Peacock"]', 'Two-track: Track A (Deepen Tech) + Track B (Break Non-Tech). CSP eligibility within 6-9 months.', '2026-04-01'),
('c1', 'Capital One', 'C1', 'Financial Services', 'fs', 're-entry', 30, 'TBD', 'Re-entering after long non-engagement. Post-Discover merger reduced vendor list. Fraud risk driving vendor scrutiny. Must rebuild trust from vendor risk to fraud-aware partner.', '["Procurement trust is the barrier","Fraud risk driving vendor scrutiny","Post-Discover merger raised vendor bar","AML/KYC regulatory pressure increasing","Third-party risk governance tightening"]', '["Fraud + false candidate exposure","AML/KYC throughput + regulatory pressure","Procurement trust + vendor consolidation","Rebuilding from vendor risk perception","Limited access beyond MSP layer"]', '["Re-enter vendor ecosystem — earn one safe yes","Rebuild procurement/ESM trust","Reposition as fraud-aware partner","Win low-risk first engagement","Expand based on performance, not persuasion"]', '["Fraud Risk/Security/Talent Risk Leaders","AML/KYC Program Owners, Transaction Monitoring","Procurement Category Leaders, ESM Leadership VP+"]', '["Fraud/Risk Protection — fraud-first screening","AML/KYC Solutions — compliant delivery","Procurement Re-Entry — controlled low-risk approach"]', '["Web — C1 landing page + proof hub","Paid Social — organic through IG SMEs","Email — FS tailored to known C1 contacts","Brand Advocacy — risk-first delivery posts","Targeted Outreach — procurement + AML/KYC leaders","Events — small local touchpoint for trust"]', '["Paid Media","Email & ABM","Web","Content & SEO","Events & Field"]', '["Grace Han"]', 'Lead with protection → Earn low-risk win → Convert proof into expansion', '2026-03-15'),
('jnj', 'Johnson & Johnson', 'JJ', 'Life Sciences', 'ls', 'key', 90, '$104M', 'Accelerate innovation across R&D, manufacturing, supply chain. Proven long-term partnership. Strong custom teams and managed service delivery. Shifting from building facilities to operationalizing them.', '["Shift to operationalizing equipment, tech, workforce","New US facility builds with major investment","AI enablement in manufacturing/operations","Continued specialized scientific talent need","LATAM global delivery expansion"]', '["Limited brand recognition in enterprise procurement","Vendor selection influenced by analyst platforms","Perceived gap in R+D and manufacturing expertise","Difficulty demonstrating credibility in technical LS","Competitive pressure from specialized consultants","Lost opportunities from executive consulting questions"]', '["Protect & expand existing delivery","Strengthen executive/procurement engagement","Position as services partner beyond staffing","Grow services across R&D, manufacturing, supply chain"]', '["Procurement/Vendor Management","Manufacturing/Operations Senior Leaders","R+D/Scientific program leadership","Supply chain/Commercialization stakeholders","Digital innovation leaders (AI + data)"]', '["FSP custom teams","LS technical staffing + consulting","Manufacturing ops + facility staffing","QA/QC + technical documentation","Data engineering + enablement","Scientific insourcing + R+D expertise","Tech transfer + commercialization","Facility stand-up + operational readiness"]', '["Content — Speed to Commercialization, GxP, Tech Transfer, AI","Brand Advocacy — consistent LS talk track","Sales Enablement — proof packs by service line","Priority Account Plays — geo-targeted + account narrative","Web — updated J+J pages with proof + CTAs"]', '["Content & SEO","Web","Paid Media","Email & ABM","Events & Field","Organic Social"]', '["Charlie Loveall","Bretlyn Morales","Chandan Barhate"]', '', '2026-04-06'),
('lilly', 'Eli Lilly', 'EL', 'Life Sciences', 'ls', 'growth', 55, 'TBD', 'Rapid GLP-1 scale-up driving M&Q demand. 80% of investment in Manufacturing & Quality. Investing heavily in AI process optimization. Saturated with vendors — needs strategic FSP partners.', '["Rapid M&Q scale-up: oral GLP-1 + future pipeline","Accelerating digital transformation + AI/data","Cost, quality, compliance pressure while scaling","New facilities: Lebanon IN, Virginia, Houston, Cork Ireland","80% of investment in Manufacturing & Quality"]', '["Rapid M&Q Scale Up — compliant workforce fast","Digital/AI Acceleration — AI-driven optimization","Cost/Compliance Pressure vs Accenture/Deloitte","Limited IG visibility beyond staffing","Not yet positioned as trusted FSP leader"]', '["Increase brand awareness + relationship depth","Position as trusted FSP (not just staffing)","Increased meetings with decision makers","Recognition as trusted FSP partner"]', '["M&Q: VP Manufacturing, Director Engineering, QA","AI/Digital: Heads of Data, AI Digital Labs","Procurement: Procurement & Category Leaders"]', '["M&Q — stand up, train, manage compliant workforce","AI/Data/Digital — build + integrate compliant AI/ML","FSP Model — customizable, scalable delivery","Engineering teams + documentation","Validation (CQV/CSV)"]', '["Web — LS page anchored in FSP model","Social/PR — organic through LS SMEs, Chandan PR","Personal Branding — sessions for Lilly sales leaders","TL Ads — targeted to top-of-funnel","IP-based customization for Lilly contacts","Email — LS tailored to known Lilly contacts","Retargeting — highlight partnership wins"]', '["Content & SEO","Web","Paid Media","Email & ABM","Organic Social","Events & Field"]', '["Charlie Loveall","Bretlyn Morales","Chandan Barhate","Bri Sundstrom"]', 'Showcase J&J/Merck delivery success, position as equally capable FSP.', '2026-04-02');

-- Tasks
INSERT INTO tasks (id, text, status, due, priority, notes, account, archived) VALUES
('t1', 'Finalize Q2 BOA campaign brief — AML thought leadership', 'In Progress', '2026-04-08', 'high', 'Need to pull latest AML metrics. Check with Grace for stakeholder updates.', 'Bank of America', false),
('t2', 'Update State Farm Insurance page with OSP + CSP language', 'Not Started', '2026-04-10', 'high', 'Coordinate with web team. Reference slides 21-23 from FS strategy deck.', 'State Farm', false),
('t3', 'Build Capital One risk-first re-entry POV', 'Not Started', '2026-04-12', 'medium', 'Blog/article format. Focus on fraud-first screening. Grace Han to review.', 'Capital One', false),
('t4', 'Prep J&J monthly deck — manufacturing proof points', 'In Progress', '2026-04-11', 'high', 'Include tech transfer metrics, facility timeline, LATAM update.', 'Johnson & Johnson', false),
('t5', 'Eli Lilly personal branding sessions for sales leaders', 'Not Started', '2026-04-14', 'medium', 'Schedule with Bretlyn and Bri. Focus on M&Q and AI/Digital for LinkedIn.', 'Eli Lilly', false),
('t6', 'Review LinkedIn ad performance — FS thought leadership', 'Not Started', '2026-04-09', 'medium', 'Pull CTR by account geo. Compare Charlotte vs ATL vs Dallas.', '', false),
('t7', 'Create State Farm proof pack: case snapshots + metrics', 'Complete', '2026-04-05', 'high', 'Completed. Includes cost optimization case and retention metrics.', 'State Farm', true);

-- Launches
INSERT INTO launches (id, name, status, account, channel, launch_date) VALUES
('l1', 'BOA AML Thought Leadership Series', 'in-progress', 'Bank of America', 'Content & SEO', '2026-04-15'),
('l2', 'State Farm Local Activation — ATL', 'upcoming', 'State Farm', 'Events & Field', '2026-04-22'),
('l3', 'Capital One Risk-First POV Campaign', 'upcoming', 'Capital One', 'Paid Media', '2026-04-28'),
('l4', 'J&J Manufacturing Proof Pack', 'in-progress', 'Johnson & Johnson', 'Web', '2026-04-12'),
('l5', 'Eli Lilly IP-Based Landing Page', 'upcoming', 'Eli Lilly', 'Web', '2026-05-01'),
('l6', 'FS Geo-Targeted LinkedIn Campaign', 'launched', 'Bank of America', 'Paid Media', '2026-03-28');

-- Goals
INSERT INTO goals (id, name, target, current, type) VALUES
('g1', 'Progress priority FS accounts', 3, 1, 'accounts'),
('g2', 'Launch 8 campaigns this quarter', 8, 4, 'launches'),
('g3', 'Complete 25 tasks this week', 25, 15, 'tasks'),
('g4', 'Build proof packs per service line', 6, 2, 'strategy'),
('g5', 'Document case studies', 5, 1, 'strategy');

-- Content
INSERT INTO content (id, title, type, channel, industry, status, activated) VALUES
('c1', '6 Reasons Cybersecurity is Critical in Finance', 'Blog', 'Content & SEO', 'FS', 'live', '["Web","Organic Social"]'),
('c2', 'Elevating CX in Financial Services', 'Blog', 'Content & SEO', 'FS', 'live', '["Web"]'),
('c3', '4 Trends in Financial Services 2026', 'Blog', 'Content & SEO', 'FS', 'live', '["Web","Email & ABM"]'),
('c4', 'Leading Business Transformation with AI', 'Blog', 'Content & SEO', 'FS', 'live', '["Web"]'),
('c5', 'Anti-Money Laundering: Compliance Bottleneck', 'Blog', 'Content & SEO', 'FS', 'live', '["Web","Paid Media"]'),
('c6', 'Smarter Science: Trends Shaping LS', 'Blog', 'Content & SEO', 'LS', 'live', '["Web","Organic Social"]'),
('c7', 'Biotech Challenges: 3 Barriers', 'Blog', 'Content & SEO', 'LS', 'live', '["Web"]'),
('c8', 'Accelerating Innovation in Life Sciences', 'Blog', 'Content & SEO', 'LS', 'live', '["Web","Organic Social"]'),
('c9', 'AI in Pharma R&D and Manufacturing', 'Blog', 'Content & SEO', 'LS', 'live', '["Web","Email & ABM"]'),
('c10', 'Life Sciences Global Delivery: Right-Shoring', 'Blog', 'Content & SEO', 'LS', 'live', '["Web"]'),
('c11', 'Intro to Life Sciences (Chandan video)', 'Video', 'Organic Social', 'LS', 'live', '["Web","Organic Social"]'),
('c12', 'State Farm POV (1-pager)', 'PDF', 'Content & SEO', 'FS', 'needed', '[]'),
('c13', 'BOA AML Case Study', 'Case Study', 'Content & SEO', 'FS', 'needed', '[]'),
('c14', 'Capital One Risk-First Re-Entry POV', 'Blog', 'Content & SEO', 'FS', 'in-progress', '[]'),
('c15', 'J&J Manufacturing Case Study', 'Case Study', 'Content & SEO', 'LS', 'needed', '[]'),
('c16', 'Eli Lilly M&Q/AI Case Study', 'Case Study', 'Content & SEO', 'LS', 'needed', '[]');
